baseURL = 'https://slack.it/'
languageCode = 'en-us'

title = 'slack.it'
enableEmoji = true
disableKinds = ["taxonomy", "term"]

[module]
[[module.imports]]
    path = "github.com/jpanther/lynx"

[params.author]
    name = "Francesco Gigli"
    headline = "geek"
    image = "avatar.jpg"
    links = [
        { bluesky = "https://bsky.app/profile/slack.it" },
        { github = "https://github.com/jaramir" },
        { facebook = "https://www.facebook.com/cesco" },
        { telegram = "https://t.me/cesco_tg" },
        { instagram = "https://www.instagram.com/jaramir" }
    ]
